---
# Pre-install role handlers
- name: restart docker
  systemd:
    name: docker
    state: restarted
  listen: "restart docker"

- name: reload systemd
  systemd:
    daemon_reload: true
  listen: "reload systemd"

- name: reboot system
  reboot:
    msg: "Reboot initiated by pre-install role after package upgrades"
  when: reboot_after_upgrade | default(false)

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
  listen: "restart systemd-resolved"

- name: apt update cache
  apt:
    update_cache: true
  listen: "apt update cache"
