---
# SSL hardening tasks

- name: Add SSL hardening headers and protocols
  blockinfile:
    path: "{{ base_nginx_conf_dir }}/ssl_hardening.conf"
    block: |
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers on;
      ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
      add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;
      server_tokens off;
    create: yes
  notify: reload nginx
