---
# DNS configuration tasks (included conditionally from main.yaml)
- name: Gather service facts
  service_facts:

- name: Check if systemd-resolved is available
  set_fact:
    has_systemd_resolved: "'systemd-resolved.service' in ansible_facts.services"

- name: Set DNS in /etc/systemd/resolved.conf
  ini_file:
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: DNS
    value: "{{ dns_nameservers | join(' ') }}"
    no_extra_spaces: true
    backup: yes
  when: has_systemd_resolved
  notify: restart systemd-resolved

- name: Ensure systemd-resolved is enabled and started
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started
  when: has_systemd_resolved


