---
# Pre-install role tasks
- name: Update package cache
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  when: update_package_cache

- name: Upgrade OS packages
  apt:
    upgrade: true
  when: upgrade_packages and ansible_pkg_mgr == 'apt'
  notify: reboot system

# Flush handlers after upgrading packages 
- name: Flush handlers after upgrading OS packages
  meta: flush_handlers

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
  when: common_packages | length > 0

- name: Include DNS configuration tasks
  include_tasks: dns-setter.yaml
  when: configure_dns

# Flush handlers after DNS configuration
- name: Flush handlers after DNS configuration
  meta: flush_handlers

# Include Docker installation tasks
- name: Include Docker installation tasks
  include_tasks: docker.yaml
  when: docker_install_method is defined

# Flush all handlers at the end
- name: Flush all handlers
  meta: flush_handlers
