---
- name: Site playbook for server setup
  hosts: all
  become: true
  roles:
    - role: pre-install
      when: install_pre_install | default(false)
    - role: zabbix.zabbix.agent
      when: install_zabbix | default(false)

- name: NGINX reverse proxy setup
  hosts: webservers
  become: true
  tags: [nginx, webservers]
  roles:
    - nginx

- name: Deploy Agent setup
  hosts: webservers
  become: true
  tags: [deploy-agent, webservers]
  roles:
    - deploy-agent
