---
- name: Site playbook for server setup
  hosts: all
  become: true
  roles:
    - role: pre-install
      when: install_pre_install
    - role: zabbix.zabbix.agent
      when: install_zabbix

- name: NGINX reverse proxy setup
  hosts: webservers
  become: true
  tags: [nginx]
  roles:
    - nginx

- name: Deploy Agent setup
  hosts: webservers
  become: true
  tags: [deploy-agent]
  roles:
    - deploy-agent
