name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop, feature/*, bugfix/* ]
  pull_request:
    branches: [ main, master, develop, feature/*, bugfix/* ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  SERVER_A_IP: "37.32.15.192"
  SERVER_B_IP: "188.121.102.61"
  DEPLOY_AGENT_PORT: "8080"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api-service
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd api-service
          python -m pytest test_api.py -v

      - name: Test API endpoints
        run: |
          cd api-service
          python api-server.py &
          sleep 5
          curl -f http://localhost:8000/health
          curl -f http://localhost:8000/
          curl -f http://localhost:8000/random
          curl -f http://localhost:8000/cons
          pkill -f api-server.py

      - name: Test Docker build
        run: |
          cd api-service
          docker build -t test-media-service .
          docker run -d --name test-container -p 8001:8000 test-media-service
          sleep 5
          curl -f http://localhost:8001/health
          docker stop test-container && docker rm test-container

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd api-service
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server A (First)
        run: |
          echo "🚀 Rolling deployment: Deploying to Server A first..."
          curl -s -X POST "http://${{ env.SERVER_A_IP }}:${{ env.DEPLOY_AGENT_PORT }}/deploy" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image_tag\": \"${{ github.sha }}\", \"registry_image\": \"ghcr.io/${{ github.repository }}\"}" \
            --max-time 60

      - name: Wait for Server A deployment
        run: |
          echo "⏳ Waiting for Server A deployment to stabilize..."
          sleep 30

      - name: Verify Server A deployment
        run: |
          echo "🔍 Verifying Server A deployment..."
          curl -f "http://${{ env.SERVER_A_IP }}:8000/health" --max-time 30
          echo "✅ Server A deployment verified successfully!"

      - name: Deploy to Server B (Second)
        run: |
          echo "🚀 Rolling deployment: Deploying to Server B..."
          curl -s -X POST "http://${{ env.SERVER_B_IP }}:${{ env.DEPLOY_AGENT_PORT }}/deploy" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image_tag\": \"${{ github.sha }}\", \"registry_image\": \"ghcr.io/${{ github.repository }}\"}" \
            --max-time 60

      - name: Wait for Server B deployment
        run: |
          echo "⏳ Waiting for Server B deployment to stabilize..."
          sleep 30

      - name: Verify Server B deployment
        run: |
          echo "🔍 Verifying Server B deployment..."
          curl -f "http://${{ env.SERVER_B_IP }}:8000/health" --max-time 30
          echo "✅ Server B deployment verified successfully!"

      - name: Final verification
        run: |
          echo "🎉 Rolling deployment completed successfully!"
          echo "Both servers are now running the new version."
