name: CI/CD Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  SERVER_A_IP: "188.121.100.34"
  SERVER_B_IP: "188.121.101.145"
  DEPLOY_AGENT_PORT: "8080"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api-service
          pip install -r requirements.txt

      - name: Start API server for testing
        run: |
          cd api-service
          echo "Starting API server for pytest..."
          python api-server.py > server.log 2>&1 &
          API_PID=$!
          echo "Server PID: $API_PID"
          echo "Waiting for server to be ready..."
          sleep 5
          
          # Verify server is running
          if ! ps -p $API_PID > /dev/null; then
            echo "❌ Server process died"
            cat server.log
            exit 1
          fi
          
          # Test if server is responding
          if ! curl -f http://localhost:8000/health >/dev/null 2>&1; then
            echo "❌ Server not responding"
            cat server.log
            exit 1
          fi
          
          echo "✅ Server is ready for testing"

      - name: Run tests
        run: |
          cd api-service
          python -m pytest test_api.py -v

      - name: Test API endpoints with curl
        run: |
          cd api-service
          echo "Testing endpoints with curl..."
          curl -f http://localhost:8000/health
          curl -f http://localhost:8000/
          curl -f http://localhost:8000/random
          curl -f http://localhost:8000/cons
          
          echo "Stopping server..."
          # Find and kill the Python API server process
          pkill -f "python api-server.py" || true
          echo "✅ Server stopped"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd api-service
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server A (First)
        run: |
          echo "🚀 Rolling deployment: Deploying to Server A first..."
          curl -s -X POST "http://${{ env.SERVER_A_IP }}:${{ env.DEPLOY_AGENT_PORT }}/deploy" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image_tag\": \"${{ github.sha }}\", \"registry_image\": \"ghcr.io/${{ github.repository }}\"}" \
            --max-time 60

      - name: Wait for Server A deployment
        run: |
          echo "⏳ Waiting for Server A deployment to stabilize..."
          sleep 30

      - name: Verify Server A deployment
        run: |
          echo "🔍 Verifying Server A deployment..."
          curl -f "http://${{ env.SERVER_A_IP }}:8000/health" --max-time 30
          echo "✅ Server A deployment verified successfully!"

      - name: Deploy to Server B (Second)
        run: |
          echo "🚀 Rolling deployment: Deploying to Server B..."
          curl -s -X POST "http://${{ env.SERVER_B_IP }}:${{ env.DEPLOY_AGENT_PORT }}/deploy" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"image_tag\": \"${{ github.sha }}\", \"registry_image\": \"ghcr.io/${{ github.repository }}\"}" \
            --max-time 60

      - name: Wait for Server B deployment
        run: |
          echo "⏳ Waiting for Server B deployment to stabilize..."
          sleep 30

      - name: Verify Server B deployment
        run: |
          echo "🔍 Verifying Server B deployment..."
          curl -f "http://${{ env.SERVER_B_IP }}:8000/health" --max-time 30
          echo "✅ Server B deployment verified successfully!"

      - name: Final verification
        run: |
          echo "🎉 Rolling deployment completed successfully!"
          echo "Both servers are now running the new version."
